### PR TITLE
Corrected some more errors

### PR DESCRIPTION
**Pull request by jlaehne**

### CODE REVIEW

**Comment by retorquere** [comment]
suggested order?

**Comment by retorquere** [comment]
I'm seeing `Physica Status Solidi AApplications and Material Science` in my tests, is that correct?

**Comment by retorquere** [comment]
The actual order is [here](https://github.com/retorquere/bibtex-parser/blob/master/build/parse-abbrevs.ts#L65)

**Comment by jlaehne** [comment]
Should be `Physica Status Solidi A: Applications and Materials Science`

The error comes out of `journalList.csv`

If `unabbrv-amendment.csv` has the highest priority that should however be taken care of.

**Comment by jlaehne** [comment]
How about 

```
  'journals/journal_abbreviations_ams.csv',
  'journals/journal_abbreviations_annee-philologique.csv',
  'journals/journal_abbreviations_dainst.csv',
  'journals/journal_abbreviations_entrez.csv',
  'journals/journal_abbreviations_ieee.csv',
  'journals/journal_abbreviations_lifescience.csv',
  'journals/journal_abbreviations_mathematics.csv',
  'journals/journal_abbreviations_mechanical.csv',
  'journals/journal_abbreviations_medicus.csv',
  'journals/journal_abbreviations_meteorology.csv',
  'journals/journal_abbreviations_sociology.csv',
  'journals/journal_abbreviations_webofscience-dots.csv',
  'journals/journal_abbreviations_webofscience.csv',
  'journals/journal_abbreviations_general.csv',
  'journals/journalList.csv',
  'journals/IEEEJournalListCode.csv',
  'journals/IEEEJournalListText.csv',
  'journals/journal_abbreviations_acs.csv',
  'journals/journal_abbreviations_geology_physics.csv',
  'unabbr-amendments.csv',
```

That puts the ones I edited last and would potentially override errors in the merged list.

**Comment by retorquere** [comment]
> The error comes out of `journalList.csv`

Well that's not great.
 
> If `unabbrv-amendment.csv` has the highest priority that should however be taken care of.

it is currently parsed last, so it should take precedence.

**Comment by jlaehne** [comment]
Did you use the latest merge of 'unabbr-amendments.csv'?

**Comment by retorquere** [comment]
I think so?

**Comment by jlaehne** [comment]
If I run it locally - both with your order or the one I proposed the `Physica Status Solidi AApplications and Material Science` does not appear!

**Comment by retorquere** [comment]
No wait, I get it. Ugh.

**Comment by retorquere** [comment]
BTW it's easier for me to paste in the order if you move the directories to the structure I have in the [actual merger](https://github.com/retorquere/bibtex-parser/blob/master/build/parse-abbrevs.ts#L65).

I'm still seeing `Physica Status Solidi AApplications and Material Science`. Strange. I need to step into the gym in 10 minutes, I'll take another look when that is over.

**Comment by jlaehne** [comment]
Sorry, I changed the local `merge.py` to work of files in my own directory.

The latest version in ` bibtex-parser/unabbr-amendments.csv` seems fine. I downloaded it again from there to use it locally.

**Comment by retorquere** [comment]
I'm an idiot. The tests *had* `Physica Status Solidi AApplications and Material Science`. They're now unchanged `physica status solidi (a)`.

**Comment by retorquere** [comment]
https://gist.github.com/4b6a113505d5316c9934649be2820443 now picks up the load order from https://github.com/retorquere/bibtex-parser/blob/master/build/load-order.json

**Pull request merged**
